"""Locate and load the pre-simulated aslscan datasets the notebooks use.

Every notebook obtains its files through :func:`load_dataset`, which resolves a dataset id (the
ids in ``pipelines/config/datasets.yaml`` and Appendix A) to a directory on disk. Resolution
order:

1. ``$ASLBOOK_DATA/<id>`` if the environment variable is set and the directory exists. This is
   how the book is built against fresh pipeline output.
2. The pooch cache, populated file by file from the GitHub release pinned by :data:`DATA_TAG`
   and the checksums in ``registry.txt``.

A dataset holds one BIDS dataset per simulation run, exactly as aslscan wrote it, under
``<id>/<run>/`` (see :class:`Run`), plus the pipeline's ``provenance.json``. In the release
each run is one tar archive, ``<id>/<run>.tar``, extracted into the cache the first time a
file of that run is asked for. The registry is generated by
``pipelines/scripts/package_release.py``; it is never edited by hand. Appendix B (the data
manifest) is rendered from the same file.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

import nibabel as nib
import numpy as np

#: Tag of the GitHub release that holds the datasets. Bumped by the release script.
DATA_TAG = "data-v0.1"
_REPO = "PennLINC/asl-book"
_REGISTRY_FILE = Path(__file__).with_name("registry.txt")


def _registry() -> dict[str, str]:
    """Parse ``registry.txt`` (pooch format: ``<path> <sha256>`` per line)."""
    entries: dict[str, str] = {}
    if not _REGISTRY_FILE.exists():
        return entries
    for line in _REGISTRY_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        path, digest = line.split()
        entries[path] = digest
    return entries


def registered_datasets() -> list[str]:
    """Dataset ids present in the registry (the first path component of each entry)."""
    return sorted({p.split("/", 1)[0] for p in _registry()})


def _local_override(dataset_id: str) -> Path | None:
    root = os.environ.get("ASLBOOK_DATA")
    if not root:
        return None
    candidate = Path(root) / dataset_id
    return candidate if candidate.is_dir() else None


def available(dataset_id: str) -> bool:
    """Whether the dataset can be loaded (locally or from the registry)."""
    return _local_override(dataset_id) is not None or dataset_id in registered_datasets()


@dataclass(frozen=True)
class Run:
    """One simulation run: a BIDS dataset written by aslscan (``sub-01/perf``), its ground
    truth (``sub-01/perf/ground-truth``), and the pipeline's tissue fractions
    (``derivatives/aslbook``). File names are relative to the run directory."""

    dataset: "Dataset"
    name: str

    @property
    def path(self) -> Path:
        return self.dataset.path / self.name

    def file(self, rel: str) -> Path:
        return self.dataset.file(f"{self.name}/{rel}")

    # -- the series -------------------------------------------------------------------
    def perf(self, suffix: str) -> Path:
        return self.file(f"sub-01/perf/sub-01_{suffix}")

    def sidecar(self) -> dict:
        return json.loads(self.perf("part-mag_asl.json").read_text())

    def context(self) -> list[str]:
        return self.perf("aslcontext.tsv").read_text().split()[1:]

    def image(self, suffix: str) -> nib.Nifti1Image:
        return nib.load(self.perf(suffix))

    def mag(self) -> np.ndarray:
        return np.asarray(self.image("part-mag_asl.nii.gz").dataobj, np.float32)

    def phase(self) -> np.ndarray:
        return np.asarray(self.image("part-phase_asl.nii.gz").dataobj, np.float32)

    def m0scan(self) -> np.ndarray:
        return np.asarray(self.image("m0scan.nii.gz").dataobj, np.float32)

    def m0scan_sidecar(self) -> dict:
        return json.loads(self.perf("m0scan.json").read_text())

    # -- the answer key ---------------------------------------------------------------
    def truth(self, name: str) -> np.ndarray:
        """A ground-truth map: ``perfusion``, ``att``, ``T1map``, ``T2map``, ``M0map``,
        ``dseg`` (int), ``deltam`` (4-D), ``deltamStatic`` (motion runs)."""
        dtype = np.int16 if name == "dseg" else np.float32
        return np.asarray(nib.load(self.file(f"sub-01/perf/ground-truth/sub-01_desc-{name}_gt.nii.gz")).dataobj, dtype)

    def truth_sidecar(self, name: str) -> dict:
        return json.loads(self.file(f"sub-01/perf/ground-truth/sub-01_desc-{name}_gt.json").read_text())

    def motion(self):
        """The applied poses as a pandas DataFrame (motion runs only)."""
        import pandas as pd

        return pd.read_csv(self.file("sub-01/perf/ground-truth/sub-01_desc-motion_gt.tsv"), sep="\t")

    def fraction(self, tissue: str) -> np.ndarray:
        """Tissue fraction (``gm``, ``wm``, ``csf``) of every acquisition voxel."""
        return np.asarray(nib.load(self.file(f"derivatives/aslbook/sub-01/perf/sub-01_label-{tissue.upper()}_probseg.nii.gz")).dataobj, np.float32)

    def fractions(self) -> dict[str, np.ndarray]:
        return {t: self.fraction(t) for t in ("gm", "wm", "csf")}

    def mask(self) -> np.ndarray:
        f = self.fractions()
        return (f["gm"] + f["wm"] + f["csf"]) > 0.5

    def simulation(self) -> dict:
        """The ``AslscanSimulation`` block of the sidecar: every resolved setting."""
        return self.sidecar()["AslscanSimulation"]

    def label_factor(self) -> float:
        """The background-suppression factor on the label-control difference (1 without
        suppression; the sidecar carries ``null`` there)."""
        return float(self.simulation().get("BackgroundSuppressionLabelFactor") or 1.0)

    def signed(self) -> np.ndarray:
        """The series as signed real images, ``magnitude * cos(phase)``: under background
        suppression the tissue can be inverted at readout, which the magnitude hides."""
        return (self.mag() * np.cos(self.phase())).astype(np.float32)


@dataclass(frozen=True)
class Dataset:
    """A resolved dataset directory."""

    id: str
    path: Path
    local: bool

    def file(self, rel: str) -> Path:
        """Path to a file inside the dataset, fetching its run's archive from the release if needed."""
        p = self.path / rel
        if p.exists():
            return p
        if self.local:
            raise FileNotFoundError(f"{rel} not found in dataset {self.id!r} at {self.path}")
        registry = _registry()
        run = rel.split("/", 1)[0]
        key = f"{self.id}/{rel}" if "/" not in rel else f"{self.id}/{run}.tar"
        if key not in registry:
            raise FileNotFoundError(f"{key} is not in the registry")
        import pooch

        processor = pooch.Untar(extract_dir=run) if key.endswith(".tar") else None
        _fetcher({key: registry[key]}).fetch(key, processor=processor)
        if not p.exists():
            raise FileNotFoundError(f"{rel} is not in the archive {key}")
        return p

    def runs(self) -> list[str]:
        if self.local:
            return sorted(p.name for p in self.path.iterdir() if p.is_dir() and p.name not in ("inputs",))
        return sorted(p.split("/")[1][: -len(".tar")] for p in _registry() if p.startswith(self.id + "/") and p.endswith(".tar"))

    def run(self, name: str | None = None) -> Run:
        """A run by name; the only run when the dataset has one."""
        if name is None:
            names = self.runs()
            if len(names) != 1:
                raise ValueError(f"dataset {self.id!r} has runs {names}; name one")
            name = names[0]
        return Run(self, name)

    def provenance(self) -> dict:
        return json.loads(self.file("provenance.json").read_text())

    def files(self) -> list[Path]:
        return sorted(p for p in self.path.rglob("*") if p.is_file())


def asset_name(key: str) -> str:
    """The release asset holding a registry key: GitHub release assets carry no directories,
    so ``/`` becomes ``__``."""
    return key.replace("/", "__")


def _fetcher(registry: dict[str, str]):
    import pooch  # imported lazily so the package works without network access

    base = f"https://github.com/{_REPO}/releases/download/{DATA_TAG}/"
    return pooch.create(
        path=pooch.os_cache("aslbook"),
        base_url=base,
        registry=registry,
        urls={k: base + asset_name(k) for k in registry},
    )


def load_dataset(dataset_id: str) -> Dataset:
    """Resolve a dataset id to a local directory, fetching from the data release if needed."""
    local = _local_override(dataset_id)
    if local is not None:
        return Dataset(dataset_id, local, True)
    registry = _registry()
    members = [p for p in registry if p.split("/", 1)[0] == dataset_id]
    if not members:
        known = ", ".join(registered_datasets()) or "none yet"
        raise KeyError(
            f"dataset {dataset_id!r} is not in the registry (known: {known}) and "
            f"$ASLBOOK_DATA/{dataset_id} does not exist. Run the pipeline in pipelines/ and set "
            f"ASLBOOK_DATA, or wait for a data release that includes it."
        )
    import pooch

    return Dataset(dataset_id, Path(pooch.os_cache("aslbook")) / dataset_id, False)
