"""Package the simulated datasets for a GitHub release and write the pooch registry.

    micromamba run -n aslbook python scripts/package_release.py [--data-root ../data] [--out ../release]

Every run of every dataset becomes one release asset, ``<dataset>/<run>.tar`` (the run's BIDS
dataset with its ground truth and derivatives; the pipeline's inputs are left out), and each
dataset's ``provenance.json`` is an asset of its own. A GitHub release asset cannot carry a
directory path, so the asset name is the registry key with ``/`` replaced by ``__``; the
loader (``aslbook.data``) maps keys back to asset names and extracts an archive on first
use. The registry (``aslbook/registry.txt``, pooch format: ``<key> <sha256>``) is written
here and never by hand. Upload with the ``gh release create`` line the script prints after
bumping ``aslbook.data.DATA_TAG``.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import tarfile
from pathlib import Path

from aslbook import data


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def tar_run(run_dir: Path, dest: Path) -> None:
    """A deterministic uncompressed tar of the run (the NIfTI files are already gzipped)."""
    with tarfile.open(dest, "w") as tar:
        for p in sorted(run_dir.rglob("*")):
            if p.is_file():
                info = tar.gettarinfo(p, arcname=p.relative_to(run_dir).as_posix())
                info.uid = info.gid = 0
                info.uname = info.gname = ""
                info.mtime = 0
                with open(p, "rb") as f:
                    tar.addfile(info, f)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-root", default="../data")
    ap.add_argument("--out", default="../release")
    ap.add_argument("--datasets", nargs="*", help="dataset ids (default: every directory under the data root)")
    a = ap.parse_args()
    root = Path(a.data_root).resolve()
    out = Path(a.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    ids = a.datasets or sorted(p.name for p in root.iterdir() if p.is_dir() and not p.name.startswith("_"))
    lines = ["# pooch registry: <dataset>/<run>.tar or <dataset>/provenance.json <sha256>",
             "# Generated by pipelines/scripts/package_release.py. Do not edit by hand."]
    total = 0
    for ds in ids:
        prov = root / ds / "provenance.json"
        if not prov.exists():
            raise SystemExit(f"{ds}: no provenance.json; run the pipeline first")
        key = f"{ds}/provenance.json"
        shutil.copy2(prov, out / data.asset_name(key))
        lines.append(f"{key} {sha256(prov)}")
        for run_dir in sorted(p for p in (root / ds).iterdir() if p.is_dir() and p.name != "inputs"):
            key = f"{ds}/{run_dir.name}.tar"
            dest = out / data.asset_name(key)
            tar_run(run_dir, dest)
            lines.append(f"{key} {sha256(dest)}")
            total += dest.stat().st_size
    reg = Path(data.__file__).with_name("registry.txt")
    reg.write_text("\n".join(lines) + "\n")
    print(f"{len(lines) - 2} assets, {total / 1e6:.0f} MB, registry at {reg}; assets in {out}")
    print(f"gh release create {data.DATA_TAG} --repo PennLINC/asl-book --title 'Simulated datasets {data.DATA_TAG}' {out.as_posix()}/*")


if __name__ == "__main__":
    main()
